In [2]:
import numpy as np

In [7]:
x = np.arange(1,13).reshape(6,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
x = np.arange(10,37, dtype=np.float64).reshape(3,3,3)
print(x)
x.dtype

[[[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]

 [[28. 29. 30.]
  [31. 32. 33.]
  [34. 35. 36.]]]


dtype('float64')

In [21]:
a = np.arange(1, 100*10+1).reshape((100,10))
x = a[(a%5==0)&(a%7==0)]
x


array([ 35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980])

In [224]:
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0, 2]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [37]:
z = np.zeros(20).reshape(4,5)
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
arr = np.zeros(10)
arr[4]=10
arr[5]=20
arr

array([ 0.,  0.,  0.,  0., 10., 20.,  0.,  0.,  0.,  0.])

In [43]:
x = np.arange(4, dtype=np.int64)
X = np.zeros(4, dtype=np.int64)
X

array([0, 0, 0, 0], dtype=int64)

In [47]:
x = np.full([2,6],6, dtype=np.uint32)
x

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]], dtype=uint32)

In [52]:
a = np.arange(2,101)
a

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [143]:
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
brr = np.array([1,2,3])
subt = arr-brr[None].T
subt

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [151]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ans= arr.copy()
ans[ans%2==1]=-1
ans

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [164]:
arr = np.array([1,2,3])
ans = np.r_[np.repeat(arr,3),np.tile(arr,3)]
ans

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [172]:
arr = np.array([2, 6, 1, 9, 10, 3, 27])
ans = arr[(arr>=5) & (arr<=10)]
ans

array([ 6,  9, 10])

In [178]:
arr = np.arange(10, 34, 1).reshape(8,3)
ans = np.array_split(arr,4)
ans

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [187]:
arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
print(arr)
ans = arr[arr[:,1].argsort(),:]
ans

[[ 8  2 -2]
 [-4  1  7]
 [ 6  3  9]]


array([[-4,  1,  7],
       [ 8,  2, -2],
       [ 6,  3,  9]])

In [193]:
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])
ans = np.dstack((x,y))
ans

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [204]:
arr = np.arange(1,10*10+1).reshape((10,10))
np.where((arr%3==0)&(arr%5==0), 'Yes', 'No')


array([['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No']],
      dtype='<U3')

In [207]:
piaic = np.arange(100)
students = np.array([5,20,50,200,301,7001])
x = np.count_nonzero(np.intersect1d(piaic,students))
x

3

In [216]:
X = np.arange(1,26).reshape(5,5)
W = np.transpose(X.copy())
b = 5
output = (X*W)+b
output

array([[  6,  17,  38,  69, 110],
       [ 17,  54, 101, 158, 225],
       [ 38, 101, 174, 257, 350],
       [ 69, 158, 257, 366, 485],
       [110, 225, 350, 485, 630]])

In [220]:
x = np.arange(1,11)
def xyz(x):
    return x*2+3-2
xyz(x)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])