In [1]:
import numpy as np

In [2]:
x=np.zeros(10)

In [3]:
y=np.arange(10,50)

In [4]:
y.shape

(40,)

In [5]:
print(y.dtype)

int32


In [6]:
print(np.__version__)

1.18.1


In [7]:
print(y.ndim)


1


In [8]:
bool_arr = np.ones(10, dtype=bool)

In [9]:
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [10]:
np.array([(1,2,3,4),(5,6,7,8)])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
arr1=np.arange(1,15)
rev_arr1=arr1[::-1]
print(rev_arr1)

[14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [13]:
arr2=np.zeros(10)
arr2[4]=1
print(arr2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1*arr2
print(arr3)

[[ 0.  8.  3.]
 [28. 10. 72.]]


In [17]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
comp_arr = np.maximum(arr1,arr2)
comp_arr

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

In [18]:
arr4 = np.arange(1,10)
arr4[1::2]

array([2, 4, 6, 8])

In [19]:
arr4 = np.arange(1,10)
arr4[arr4%2==1]=-1
arr4

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
arr = np.arange(10)
arr[4:8]=12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

In [21]:
arr5=np.ones((4,4))
arr5[1:-1, 1:-1]=0
arr5

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,:]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr6=np.arange(10).reshape(5,2)
arr6[0]


array([0, 1])

In [25]:
arr6=np.arange(10).reshape(5,2)
arr6[1,1]

3

In [26]:
arr6=np.arange(10).reshape(2,5)
arr6[:2,2]

array([2, 7])

In [27]:
arr7 = np.random.randn(10,10)
arr7_int = arr7.astype(np.int8)
print(arr7_int)
max_arr7=np.max(arr7_int)
print("Maximum Value=",max_arr7)
min_arr7=np.min(arr7_int)
print("Minimum Value=",min_arr7)


[[-1  0  1  0  0  0  0  0  0  0]
 [-1  0  1  0  1  0  0  0  0 -1]
 [ 0  0  1  0 -1  0 -1  1 -1  0]
 [ 0  0  0 -1  0 -1  1 -1  0  0]
 [ 0  0  0  0  0  0  0  0  0  2]
 [ 0  0  0  0  0  0 -1  0  0  0]
 [ 1  0  0 -1  0  0  1 -1  1  0]
 [-1  0  0  0  0  0 -1  0  0 -1]
 [ 0  0  0  0  1  0  1  1  0  0]
 [ 0 -2  0  0  0  0  0  0  0  1]]
Maximum Value= 2
Minimum Value= -2


In [57]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [58]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [70]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print (data)
data[names!='Will']
data[names!='Joe']

[[ 0.89094608 -0.88676567 -0.74023061  0.04062657]
 [-1.71650703 -0.48330729 -1.77319675 -0.20391256]
 [ 0.08190025  1.09354294 -0.57824986 -2.18544349]
 [ 0.21049941 -0.37548132  0.0270535   0.3786873 ]
 [-0.83012546  1.10334565  0.74006251  1.10555696]
 [-1.9952     -2.0729522   3.21054307 -1.29589055]
 [ 0.34046412 -0.21614778 -1.19686535  0.06041176]]


array([[ 0.89094608, -0.88676567, -0.74023061,  0.04062657],
       [ 0.08190025,  1.09354294, -0.57824986, -2.18544349],
       [ 0.21049941, -0.37548132,  0.0270535 ,  0.3786873 ],
       [-0.83012546,  1.10334565,  0.74006251,  1.10555696]])

In [84]:
arr8=np.random.uniform(1,16, size=(2,2,4))
arr8

array([[[ 6.92617546, 13.90411333,  5.26150478,  1.60553127],
        [ 3.43432348, 15.81438017,  6.73485856, 12.29056764]],

       [[ 3.92250345,  4.8094435 ,  4.48473314, 10.14522732],
        [ 3.33129524, 11.09597617, 11.95615061,  9.50984141]]])

In [118]:
swap_arr=np.swapaxes(arr8,0,1)
swap_arr

array([[[ 6.92617546, 13.90411333,  5.26150478,  1.60553127],
        [ 3.92250345,  4.8094435 ,  4.48473314, 10.14522732]],

       [[ 3.43432348, 15.81438017,  6.73485856, 12.29056764],
        [ 3.33129524, 11.09597617, 11.95615061,  9.50984141]]])

In [117]:
arr8.transpose(1,0,2)

array([[[ 6.92617546, 13.90411333,  5.26150478,  1.60553127],
        [ 3.92250345,  4.8094435 ,  4.48473314, 10.14522732]],

       [[ 3.43432348, 15.81438017,  6.73485856, 12.29056764],
        [ 3.33129524, 11.09597617, 11.95615061,  9.50984141]]])

In [162]:
arr10 = np.arange(0.1,1,0.1)
print(arr10)
sqrt_arr = np.sqrt(arr10)
sqrt_arr[sqrt_arr<0.5]=0
sqrt_arr

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


array([0.        , 0.        , 0.54772256, 0.63245553, 0.70710678,
       0.77459667, 0.83666003, 0.89442719, 0.9486833 ])

In [167]:
arr11=np.random.randn(12)*10
arr12=np.random.randn(12)*10
print(arr11)
print(arr12)

np.maximum(arr11,arr12)


[  2.6399983   -5.9259809  -21.3063534    4.82785904   5.56652433
  -2.91059332 -15.07379007  10.15993498   1.28091629  -8.34347672
  -1.32656388   6.77224743]
[ 7.57912359  1.25036468  1.96171632 -1.30202912 -4.18094156  1.37595371
 -2.66303625  9.12990335 17.535493    1.73975437 -3.57711632 -2.6516446 ]


array([ 7.57912359,  1.25036468,  1.96171632,  4.82785904,  5.56652433,
        1.37595371, -2.66303625, 10.15993498, 17.535493  ,  1.73975437,
       -1.32656388,  6.77224743])

In [168]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [175]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [197]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray[:,1]=newColumn
print("\nAfter Replacing Column2 with newColumn:\n",sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]

After Replacing Column2 with newColumn:
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


In [211]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
(np.dot(x,y))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

In [223]:
arr13=np.random.uniform(1,20, size=(1,20))
print(arr13)
np.cumsum(arr13)


[[ 1.86335447 18.75110866 16.17274625 12.65898779  3.40610076 11.41728611
   4.16652319  6.02581586 15.57573589  2.21262069  8.30955309 15.82537134
  11.69514631  1.65219177  6.67706007  8.17678738 18.25145111  4.51177428
  14.50120478  2.24403804]]


array([  1.86335447,  20.61446314,  36.78720938,  49.44619717,
        52.85229793,  64.26958404,  68.43610723,  74.46192309,
        90.03765898,  92.25027967, 100.55983276, 116.3852041 ,
       128.08035041, 129.73254219, 136.40960226, 144.58638964,
       162.83784075, 167.34961503, 181.85081981, 184.09485785])