# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
y=np.arange(10,50)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
y.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
print(y.dtype)

int32


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)

1.18.1


7. Print the dimension of the array in question 3


In [7]:
print(y.ndim)

1


8. Create a boolean array with all the True values

In [8]:
bool_arr = np.ones(10, dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [9]:
np.array([(1,2,3,4),(5,6,7,8)])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

10. Create a three dimensional array



In [10]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
arr1=np.arange(1,15)
rev_arr1=arr1[::-1]
rev_arr1

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
arr2=np.zeros(10)
arr2[4]=1
arr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1*arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
comp_arr = np.maximum(arr1,arr2)
comp_arr

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr4 = np.arange(1,10)
arr4[1::2]

array([2, 4, 6, 8])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr4 = np.arange(1,10)
arr4[arr4%2==1]=-1
arr4

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[4:8]=12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr5=np.ones((4,4))
arr5[1:-1, 1:-1]=0
arr5

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,:]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr6=np.arange(10).reshape(2,5)
arr6[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr6=np.arange(10).reshape(2,5)
arr6[1,1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr6=np.arange(10).reshape(2,5)
arr6[:2,2]

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr7 = np.random.randn(10,10)
arr7_int = arr7.astype(np.int8)
print(arr7_int)
max_arr7=np.max(arr7_int)
print("Maximum Value=",max_arr7)
min_arr7=np.min(arr7_int)
print("Minimum Value=",min_arr7)

[[ 0  0  0  0  0  0 -2  0  0 -1]
 [ 0  0  1  0  0  0  0  1 -1  0]
 [ 0  0  1  0  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0 -1  0  0 -1  0]
 [ 0  0  0  0  0  1  0  1 -1  0]
 [-1  0  0  0 -1  1  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  1  0  0 -1]
 [ 0  0 -1  0  0  0 -1  1  1 -2]]
Maximum Value= 1
Minimum Value= -2


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print (data)
data[names!='Will']

[[ 0.8159291  -1.00695364 -1.89927014 -0.02022194]
 [ 0.97959301  0.8170245   0.75186921 -0.59172776]
 [ 0.16603748 -0.15179212 -0.84846241  1.91432552]
 [-0.13048754 -0.61147293 -0.58989462 -0.97831844]
 [-1.05430875 -0.01462772  0.16223639 -0.12597195]
 [ 0.02219049  0.99069981 -0.49205878 -1.60307822]
 [-0.6522429   0.76692535  1.64018184 -2.9727406 ]]


array([[ 0.8159291 , -1.00695364, -1.89927014, -0.02022194],
       [ 0.97959301,  0.8170245 ,  0.75186921, -0.59172776],
       [-0.13048754, -0.61147293, -0.58989462, -0.97831844],
       [ 0.02219049,  0.99069981, -0.49205878, -1.60307822],
       [-0.6522429 ,  0.76692535,  1.64018184, -2.9727406 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print (data)
data[names!='Will']
data[names!='Joe']

[[-0.38263612  1.03105144  0.67574192 -0.57502612]
 [ 1.80878884  0.37644829  0.2697825  -0.73388099]
 [-1.08394808  0.77345015 -0.58251278 -0.71421544]
 [ 0.19949969 -0.22337927 -0.56158734 -1.45003649]
 [-0.8073109   1.88110448  0.5502287   0.96520166]
 [-1.04499884  1.70399919 -0.65979249 -0.45208267]
 [ 1.46917918 -0.7576918  -1.20507279  0.29166398]]


array([[-0.38263612,  1.03105144,  0.67574192, -0.57502612],
       [-1.08394808,  0.77345015, -0.58251278, -0.71421544],
       [ 0.19949969, -0.22337927, -0.56158734, -1.45003649],
       [-0.8073109 ,  1.88110448,  0.5502287 ,  0.96520166]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr8=np.random.uniform(1,15, size=(5,3))
arr8

array([[11.05503543,  2.61730155,  4.5589197 ],
       [ 1.48942345, 12.29149825,  5.55989157],
       [ 6.17507296, 14.63015181,  9.77898461],
       [ 7.3815388 , 11.41060447,  3.44206969],
       [ 2.65792359,  7.12303075, 11.59371414]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr9=np.random.uniform(1,16, size=(2,2,4))
arr9

array([[[ 4.07068384,  9.29123844,  3.15278091,  5.81962469],
        [12.70268256,  4.92281081,  5.92740427, 13.56228938]],

       [[15.86437061,  1.96867026,  8.59848034,  2.04259878],
        [ 2.92662319, 12.10895744,  5.65406388,  8.29349592]]])

33. Swap axes of the array you created in Question 32

In [34]:
swap_arr=np.swapaxes(arr9,0,1)
swap_arr

array([[[ 4.07068384,  9.29123844,  3.15278091,  5.81962469],
        [15.86437061,  1.96867026,  8.59848034,  2.04259878]],

       [[12.70268256,  4.92281081,  5.92740427, 13.56228938],
        [ 2.92662319, 12.10895744,  5.65406388,  8.29349592]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [36]:
arr10 = np.arange(0.1,1,0.1)
print(arr10)
sqrt_arr = np.sqrt(arr10)
sqrt_arr[sqrt_arr<0.5]=0
sqrt_arr

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


array([0.        , 0.        , 0.54772256, 0.63245553, 0.70710678,
       0.77459667, 0.83666003, 0.89442719, 0.9486833 ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [37]:
arr11=np.random.randn(12)*10
arr12=np.random.randn(12)*10
print(arr11)
print(arr12)
np.maximum(arr11,arr12)

[ -1.53252834  -2.02380131   1.39285888  -2.92727977  13.09521553
   8.97279254  -8.52545476 -20.57249993 -17.44857747   4.74900373
  -8.83501984  -0.1334253 ]
[  5.80740942  15.47062633   4.58441052  16.64255259 -15.6236543
  -5.71955651  -3.5482653   16.79379982   2.84889545 -13.21183897
   4.31423748  -7.24397165]


array([ 5.80740942, 15.47062633,  4.58441052, 16.64255259, 13.09521553,
        8.97279254, -3.5482653 , 16.79379982,  2.84889545,  4.74900373,
        4.31423748, -0.1334253 ])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [41]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
a=np.setdiff1d(a,b)
print(a)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [42]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray[:,1]=newColumn
print("\nAfter Replacing Column2 with newColumn:\n",sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]

After Replacing Column2 with newColumn:
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [43]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
(np.dot(x,y))

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [47]:
arr13=np.random.uniform(1,20, size=(1,20))
print(arr13)
cumsum_arr=np.cumsum(arr13)
print("Cumulative Sum:",cumsum_arr[19])

[[12.58551993  1.84396387  6.79250097  1.28090033 16.27185797 19.38738499
  15.09293257  4.36865987 14.01794006 19.66420111  2.60199285  1.54682933
   2.27101989 19.77858453  5.47090966 13.9930606   3.77169506  4.80637854
  14.49557328 11.37311165]]
Cumulative Sum: 191.41501706044153
